Add ability to update quantity & override resource mapping
timothydc/laravel-lightspeed-retail-api pull request #21
Opened 2022-08-23 17:37 UTC by HarryLee186

Pretty basic functionality at the moment, but this will allow a user to add a default quantity to their products.

This requires a ShopID to be present, so I've also added the ability to override the resource mapping so people can provide a numeric ID here without saving it to the database. I'm open to any ideas on how this could be improved, perhaps we should use a callback function instead for overriding?

2022-08-25 18:24 UTC, HarryLee186 commented
I'm interested as to how best we can sync the quantity on update of a product. It looks like we need to provide an `itemShopID` which seems randomly generated when the product is created on Lightspeed. Example PUT body would be:

```
{
	"ItemShops": {
		"ItemShop": {
			"itemShopID": 11111,
			"qoh": 4
		}
	}
}
```

2022-08-25 18:52 UTC, HarryLee186 commented
I've addressed the updating of product quantities with [cca5aec](https://github.com/HarryLee186/laravel-lightspeed-retail-api/commit/cca5aec305bb0187e117a07a98fc03dbea4798ab). It's a little bit janky, so I'm open to ideas on how we could clean this up. In short, it:

- Makes an API call to get the Item
- Gets the Shop relation and gets the itemShopID
- Uses this in the payload to update the correct shop, using the user-defined $shopId as a way to know which shop to update

2022-08-25 18:53 UTC, timothydc commented
> I'm interested as to how best we can sync the quantity on update of a product. It looks like we need to provide an `itemShopID` which seems randomly generated when the product is created on Lightspeed. Example PUT body would be:
> 
> ```
> {
> 	"ItemShops": {
> 		"ItemShop": {
> 			"itemShopID": 11111,
> 			"qoh": 4
> 		}
> 	}
> }
> ```

You would have to do a `GET` before you update, or save the IDs locally I guess.
Or you could try and see if LS is smart enough to update the right `ItemShop` object when you provide the item and the shop ID :)

2022-08-25 18:54 UTC, timothydc commented
> I've addressed the updating of product quantities with [cca5aec](https://github.com/HarryLee186/laravel-lightspeed-retail-api/commit/cca5aec305bb0187e117a07a98fc03dbea4798ab). It's a little bit janky, so I'm open to ideas on how we could clean this up. In short, it:
> 
> * Makes an API call to get the Item
> * Gets the Shop relation and gets the itemShopID
> * Uses this in the payload to update the correct shop, using the user-defined $shopId as a way to know which shop to update

I would move all your code in `adjustQuantityPayload` to an accessor on your model, like in my example.
That gives you a lot more freedom!

2022-08-29 12:30 UTC, HarryLee186 commented
@timothydc Would you be able to point me to where your example is? I'm a little unsure on which part you're referring to.

2022-09-15 07:45 UTC, timothydc commented
> @timothydc Would you be able to point me to where your example is? I'm a little unsure on which part you're referring to.

@HarryLee186 Did you see my review ping here? https://github.com/timothydc/laravel-lightspeed-retail-api/pull/21/files/7cc7e945fd30f7a64fa58bb04ff7934ff9d0b333

2022-09-16 16:28 UTC, HarryLee186 commented
@timothydc Following that link takes me to the files to be reviewed, but doesn't show me any pings or comments.

2023-01-30 15:42 UTC, timothydc requested changes

2023-01-30 15:42 UTC, timothydc commented on src/Actions/GenerateRetailPayloadAction.php
> +                }
@HarryLee186 Does it have to be numeric though? It feels weird to have a numeric check there.

What is we define our resource mapping like this:

```php
// in your model class
public static function getLightspeedRetailResourceMapping(): array
{
    return [
        ...
        ResourceItem::$itemShops => ['itemShopData', null],
    ];

}
```

And then we do something like:

```php
// in GenerateRetailPayloadAction.php
if ($value && Str::contains($value, '.') === true) {
    ...
} elseif (is_null(value)) {

    if (Str::endsWith('Attribute')) {
        // for accessors up to L9
        $resourceColumnValue = $model->$localAttribute;
    } else {
        // accessors for L9 and beyond
        $localAttribute = Str::snake($localAttribute);
        $resourceColumnValue = $model->$localAttribute;
    }

} else {
    $resourceColumnValue = $model->$value;
}
```

That gives you the freedom to use https://laravel.com/docs/eloquent-mutators#accessors-and-mutators. I am not 100% certain about the backwards compatibility, since the Laravel attributes changes.

```php
// in your model class
protected function itemShopData(): Attribute {}
```

And then you can build your `ItemShops` payload directly in your model, instead of adding more logic to the `formatPayload` method.

The above should give you more freedom.

Let me know what you think!

2023-01-30 15:42 UTC, timothydc commented on src/Actions/GenerateRetailPayloadAction.php
> +                }
@HarryLee186 The example above!

2023-11-13 12:42 UTC, closed without merging