Resource Item as Label
timothydc/laravel-lightspeed-retail-api pull request #22
Opened 2022-08-23 18:29 UTC by HarryLee186

- Allows a user to get a label using the [DisplayTemplate Label](https://developers.lightspeedhq.com/retail/endpoints/DisplayTemplate-Label) endpoint
- Updates the ApiClient to support header and file type overrides for get requests, as well as more accommodation for our Item Label resource. At some point, it would be good to update the other request functions to be in line with these updates.

2022-08-23 18:32 UTC, HarryLee186 commented on src/Services/ApiClient.php
> +        //If we're requesting HTMl, just return our HTML
```suggestion
        //If we're requesting HTML, just return our HTML
```

2022-08-25 16:38 UTC, HarryLee186 commented
@timothydc I'd love your feedback on this & #21 when you get a moment :)

2023-01-30 15:41 UTC, timothydc requested changes

2023-01-30 15:41 UTC, timothydc commented on src/Services/ApiClient.php
> +        $responseObject = Http::withHeaders(array_merge(['Accept' => 'application/json'], $additionalHeaders))
@HarryLee186 I wouldn't pass the headers via the `get` method, that might get a bit bloated.

Maybe like this:

```php
// in ApiClient.php
protected array $additionalHeaders = [];

public function withHeaders(array $headers): self
{
   $this->additionalHeaders = $headers;
   return $this;
}
```

Like `LightspeedRetailApi::api()->withHeaders([...])->get();`

2023-01-30 15:41 UTC, timothydc commented on src/Services/ApiClient.php
> +        //In some cases, Lightspeed might return an array key with a resource name that is slightly different to what we expect
Do you have an example of this?

2023-01-30 15:41 UTC, timothydc commented on src/Services/ApiClient.php
> +    private function getUrl(string $resource = null, int $id = null, string $extension = null): string
Do you still need to provide an extension when you have set an alternative `Content-Type` ?

Is see that the docs say:

> Use the .html emitter or Content-Type: text/html header to get an HTML rendering

Emphasis on the "or".

2023-11-13 12:42 UTC, closed without merging